# Generated by Django 4.1.7 on 2023-02-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_applicationnewssource_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationnewssource',
            name='batch',
        ),
    ]
