# Generated by Django 4.0.3 on 2022-05-02 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('from_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Email Contents',
            },
        ),
        migrations.CreateModel(
            name='StatusEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('application_submitted', 'Application Submitted'), ('awaiting_payment', 'Awaiting Payment'), ('under_review', 'Under Review'), ('payment_verified', 'Payment Verified'), ('payment_completed', 'Payment Completed')], max_length=40, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('mail_from', models.EmailField(max_length=254)),
                ('template', models.FileField(blank=True, null=True, upload_to='templates/emails/')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Status Emails',
            },
        ),
        migrations.CreateModel(
            name='StatusSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('application_submitted', 'Application Submitted'), ('awaiting_payment', 'Awaiting Payment'), ('under_review', 'Under Review'), ('payment_verified', 'Payment Verified'), ('payment_completed', 'Payment Completed')], max_length=40, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Status SMS',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('occupation', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('email', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='StatusEmailFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='templates/emails/attachments/')),
                ('status_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='newsletter.statusemail')),
            ],
            options={
                'verbose_name_plural': 'Status Email Files',
            },
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('subscriber', models.ManyToManyField(to='newsletter.subscriber')),
            ],
            options={
                'verbose_name_plural': 'Newsletters',
            },
        ),
    ]
