# Generated by Django 4.0.3 on 2022-05-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusemail',
            name='status',
            field=models.CharField(blank=True, choices=[('application_submitted', 'Application Submitted'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_payment_reminder', 'Awaiting Payment Reminder'), ('under_review', 'Under Review'), ('payment_verified', 'Payment Verified'), ('payment_completed', 'Payment Completed')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='statussms',
            name='status',
            field=models.CharField(blank=True, choices=[('application_submitted', 'Application Submitted'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_payment_reminder', 'Awaiting Payment Reminder'), ('under_review', 'Under Review'), ('payment_verified', 'Payment Verified'), ('payment_completed', 'Payment Completed')], max_length=40, null=True),
        ),
    ]
