# Generated by Django 4.0.3 on 2022-05-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_statusemail_status_alter_statussms_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusemail',
            name='status',
            field=models.CharField(blank=True, choices=[('application_submitted', 'Application Submitted'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_payment_reminder', 'Awaiting Payment Reminder'), ('under_review', 'Under Review'), ('payment_completed', 'Payment Completed'), ('photo_submitted', 'Photo and Signature Uploaded'), ('download_admit', 'Download Admit'), ('cancel_application', 'Cancel Application')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='statussms',
            name='status',
            field=models.CharField(blank=True, choices=[('application_submitted', 'Application Submitted'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_payment_reminder', 'Awaiting Payment Reminder'), ('under_review', 'Under Review'), ('payment_completed', 'Payment Completed'), ('photo_submitted', 'Photo and Signature Uploaded'), ('download_admit', 'Download Admit'), ('cancel_application', 'Cancel Application')], max_length=40, null=True),
        ),
    ]
