# Generated by Django 4.0.3 on 2022-06-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_alter_statusemail_status_alter_statussms_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusemail',
            name='status',
            field=models.CharField(blank=True, choices=[('application_submitted', 'Application Submitted'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_payment_reminder', 'Awaiting Payment Reminder'), ('under_review', 'Under Review'), ('payment_completed', 'Payment Completed'), ('photo_submitted', 'Photo and Signature Uploaded'), ('download_admit', 'Download Admit'), ('payment_verified', 'Payment Verified-FORSMS'), ('payment_not_verified', 'Payment Not Verified-FORSMS'), ('application_cancelled', 'Application Cancelled'), ('remind_upload_photo', 'Remind To Upload Photo'), ('notify_venue_as_sylhet', 'Notify Venue as Sylhet'), ('notify_venue_as_dhaka', 'Notify Venue as Dhaka'), ('notify_dummy_venue_location', 'Notify  Dummy Venue Location')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='statussms',
            name='status',
            field=models.CharField(blank=True, choices=[('application_submitted', 'Application Submitted'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_payment_reminder', 'Awaiting Payment Reminder'), ('under_review', 'Under Review'), ('payment_completed', 'Payment Completed'), ('photo_submitted', 'Photo and Signature Uploaded'), ('download_admit', 'Download Admit'), ('payment_verified', 'Payment Verified-FORSMS'), ('payment_not_verified', 'Payment Not Verified-FORSMS'), ('application_cancelled', 'Application Cancelled'), ('remind_upload_photo', 'Remind To Upload Photo'), ('notify_venue_as_sylhet', 'Notify Venue as Sylhet'), ('notify_venue_as_dhaka', 'Notify Venue as Dhaka'), ('notify_dummy_venue_location', 'Notify  Dummy Venue Location')], max_length=40, null=True),
        ),
    ]
