# Generated by Django 4.0.3 on 2022-04-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequest',
            name='status',
            field=models.CharField(choices=[('responded', 'Responded'), ('not_responded', 'Not Responded')], default='not_responded', max_length=25),
        ),
    ]
