# Generated by Django 4.1.7 on 2023-02-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_smsrequest_options_phonerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='batch',
            field=models.CharField(default='BBA10', max_length=25),
        ),
    ]
