# Generated by Django 4.1.7 on 2023-02-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chatrequest_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='response_via',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='response_via_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
