# Generated by Django 4.1.7 on 2023-02-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chatrequest_response_chatrequest_response_via_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='application_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
