# Generated by Django 4.1.7 on 2023-02-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chatrequest_application_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonerequest',
            old_name='message',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='smsrequest',
            old_name='message',
            new_name='problem',
        ),
        migrations.AddField(
            model_name='phonerequest',
            name='application_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phonerequest',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phonerequest',
            name='response_via',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phonerequest',
            name='response_via_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smsrequest',
            name='application_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smsrequest',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smsrequest',
            name='response_via',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smsrequest',
            name='response_via_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
