# Generated by Django 4.1.7 on 2023-02-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_rename_message_phonerequest_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonerequest',
            name='batch',
            field=models.CharField(choices=[('BBA10', 'BBA10'), ('BBA11', 'BBA11')], default='BBA11', max_length=25),
        ),
        migrations.AddField(
            model_name='smsrequest',
            name='batch',
            field=models.CharField(choices=[('BBA10', 'BBA10'), ('BBA11', 'BBA11')], default='BBA11', max_length=25),
        ),
    ]
