# Generated by Django 4.1.7 on 2023-02-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_phonerequest_batch_smsrequest_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='problem_type',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('during_application', 'During Application'), ('circular', 'Circular'), ('payment', 'Payment'), ('photo_upload', 'Photo Upload'), ('others', 'Others')], default='others', max_length=255, null=True),
        ),
    ]
