# Generated by Django 4.1.7 on 2023-02-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_chatrequest_problem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonerequest',
            name='problem_type',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('during_application', 'During Application'), ('circular', 'Circular'), ('payment', 'Payment'), ('photo_upload', 'Photo Upload'), ('others', 'Others')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smsrequest',
            name='problem_type',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('during_application', 'During Application'), ('circular', 'Circular'), ('payment', 'Payment'), ('photo_upload', 'Photo Upload'), ('others', 'Others')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='problem_type',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('during_application', 'During Application'), ('circular', 'Circular'), ('payment', 'Payment'), ('photo_upload', 'Photo Upload'), ('others', 'Others')], max_length=255, null=True),
        ),
    ]
