# Generated by Django 4.1.7 on 2023-05-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_phonerequest_problem_type_smsrequest_problem_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequest',
            name='problem_type',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('during_application', 'During Application'), ('circular', 'Circular'), ('payment', 'Payment'), ('photo_upload', 'Photo Upload'), ('open_payment_window', 'Open Payment Window'), ('others', 'Others')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='phonerequest',
            name='problem_type',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('during_application', 'During Application'), ('circular', 'Circular'), ('payment', 'Payment'), ('photo_upload', 'Photo Upload'), ('open_payment_window', 'Open Payment Window'), ('others', 'Others')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smsrequest',
            name='problem_type',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('during_application', 'During Application'), ('circular', 'Circular'), ('payment', 'Payment'), ('photo_upload', 'Photo Upload'), ('open_payment_window', 'Open Payment Window'), ('others', 'Others')], max_length=255, null=True),
        ),
    ]
