# Generated by Django 4.0.3 on 2022-06-21 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=15)),
                ('guardians_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('study_level', models.CharField(choices=[('hsc', 'HSC'), ('a_level', 'A-Level')], max_length=20)),
                ('hsc_reg_no', models.CharField(blank=True, max_length=55)),
                ('hsc_roll', models.CharField(blank=True, max_length=20)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('hsc_board', models.CharField(blank=True, max_length=55)),
                ('hsc_group', models.CharField(blank=True, choices=[('science', 'Science'), ('commerce', 'Commerce'), ('arts', 'Arts')], max_length=10)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('passing_year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('district', models.CharField(max_length=75)),
                ('address', models.CharField(max_length=75)),
                ('quota', models.CharField(default='general', max_length=75)),
            ],
            options={
                'unique_together': {('phone', 'date_of_birth')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('verified_information', models.TextField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicationverification', to='application.application')),
            ],
            options={
                'verbose_name_plural': 'Application Verification',
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('application_submitted', 'Application Submitted'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_payment_reminder', 'Awaiting Payment Reminder'), ('under_review', 'Under Review'), ('payment_completed', 'Payment Completed'), ('photo_submitted', 'Photo and Signature Uploaded'), ('download_admit', 'Download Admit'), ('payment_verified', 'Payment Verified-FORSMS'), ('payment_not_verified', 'Payment Not Verified-FORSMS'), ('application_cancelled', 'Application Cancelled'), ('remind_upload_photo', 'Remind To Upload Photo'), ('notify_venue_as_sylhet', 'Notify Venue as Sylhet'), ('notify_venue_as_dhaka', 'Notify Venue as Dhaka'), ('notify_dummy_venue_location', 'Notify  Dummy Venue Location')], default='application_submitted', max_length=100)),
                ('message', models.TextField(blank=True)),
                ('mail_sent_awaiting_payment', models.BooleanField(default=False, editable=False)),
                ('mail_sent_payment_completed', models.BooleanField(default=False, editable=False)),
                ('mail_sent_download_admit_card', models.BooleanField(default=False, editable=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
            ],
            options={
                'verbose_name_plural': 'Application Status',
            },
        ),
        migrations.CreateModel(
            name='ApplicationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(max_length=55, unique=True)),
                ('verified', models.BooleanField(blank=True, null=True, verbose_name='Payment Verified')),
                ('mail_sent', models.BooleanField(default=False, editable=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicationpayment', to='application.application')),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='ApplicantExtraInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Birth Place')),
                ('marital_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Marital Status')),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Permanent Address')),
                ('identification_mark', models.CharField(blank=True, max_length=255, null=True, verbose_name='Identification Mark')),
                ('blood_group', models.CharField(max_length=5, verbose_name='Blood Group')),
                ('name_father', models.CharField(max_length=255, verbose_name='Name of Father')),
                ('work_place_father', models.CharField(blank=True, max_length=255, null=True, verbose_name='Work Place of Father')),
                ('designation_father', models.CharField(blank=True, max_length=255, null=True, verbose_name='Designation of Father')),
                ('national_id_father', models.CharField(blank=True, max_length=255, null=True, verbose_name='National ID of Father')),
                ('phone_father', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone of Father')),
                ('name_mother', models.CharField(max_length=255, verbose_name='Name of Mother')),
                ('work_place_mother', models.CharField(blank=True, max_length=255, null=True, verbose_name='Work Place of Mother')),
                ('designation_mother', models.CharField(blank=True, max_length=255, null=True, verbose_name='Designation of Mother')),
                ('national_id_mother', models.CharField(blank=True, max_length=255, null=True, verbose_name='National ID of Mother')),
                ('phone_mother', models.CharField(blank=True, max_length=255, verbose_name='Phone of Mother')),
                ('study_level', models.CharField(default='ssc', max_length=20)),
                ('ssc_roll', models.CharField(blank=True, max_length=20, null=True, verbose_name='SSC Roll')),
                ('ssc_board', models.CharField(blank=True, max_length=55, null=True, verbose_name='SSC Board')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='GPA')),
                ('ssc_group', models.CharField(blank=True, max_length=55, null=True, verbose_name='SSC Group')),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_personal', models.ImageField(upload_to='application/photos/applicants/', verbose_name='Photo of Applicant')),
                ('photo_signature', models.ImageField(upload_to='application/photos/signatures/', verbose_name='Photo of Signature')),
                ('passing_year', models.IntegerField(blank=True, null=True)),
                ('admit_card', models.FileField(blank=True, null=True, upload_to='application/admit_cards/', verbose_name='Admit Card')),
                ('serial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Roll')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='application.application')),
            ],
            options={
                'verbose_name': 'Application Extra Information',
                'verbose_name_plural': 'Application Extra Information',
            },
        ),
    ]
