# Generated by Django 4.1.7 on 2023-02-17 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_passing_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('application_submitted', 'Application Submitted'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_payment_reminder', 'Awaiting Payment Reminder'), ('under_review', 'Under Review'), ('payment_completed', 'Payment Completed'), ('photo_submitted', 'Photo and Signature Uploaded'), ('download_admit', 'Download Admit'), ('payment_verified', 'Payment Verified-FORSMS'), ('payment_not_verified', 'Payment Not Verified-FORSMS'), ('application_cancelled', 'Application Cancelled'), ('remind_upload_photo', 'Remind To Upload Photo'), ('notify_venue_as_sylhet', 'Notify Venue as Sylhet'), ('notify_venue_as_dhaka', 'Notify Venue as Dhaka'), ('notify_dummy_venue_location', 'Notify  Dummy Venue Location')], max_length=100)),
                ('new_status', models.CharField(choices=[('application_submitted', 'Application Submitted'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_payment_reminder', 'Awaiting Payment Reminder'), ('under_review', 'Under Review'), ('payment_completed', 'Payment Completed'), ('photo_submitted', 'Photo and Signature Uploaded'), ('download_admit', 'Download Admit'), ('payment_verified', 'Payment Verified-FORSMS'), ('payment_not_verified', 'Payment Not Verified-FORSMS'), ('application_cancelled', 'Application Cancelled'), ('remind_upload_photo', 'Remind To Upload Photo'), ('notify_venue_as_sylhet', 'Notify Venue as Sylhet'), ('notify_venue_as_dhaka', 'Notify Venue as Dhaka'), ('notify_dummy_venue_location', 'Notify  Dummy Venue Location')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicationstatuschangelog', to='application.applicationstatus')),
            ],
        ),
    ]
