# Generated by Django 4.1.7 on 2023-02-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_applicationstatuschangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='information_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='programme',
            field=models.CharField(blank=True, choices=[('BBA', 'BBA'), ('MBA', 'MBA')], max_length=255, null=True),
        ),
    ]
