# Generated by Django 4.1.7 on 2023-02-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_application_information_source_application_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='batch',
            field=models.CharField(default='BBA10', max_length=25),
        ),
    ]
