# Generated by Django 4.1.7 on 2023-02-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_application_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='batch',
            field=models.CharField(choices=[('BBA10', 'BBA10'), ('BBA11', 'BBA11')], default='BBA11', max_length=25),
        ),
    ]
