# Generated by Django 4.1.7 on 2023-02-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_application_batch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantextrainformation',
            options={'verbose_name': 'Application Extra Information: Photo Upload Phase', 'verbose_name_plural': 'Application Extra Information: Photo Upload Phase'},
        ),
    ]
