# Generated by Django 4.1.7 on 2023-03-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_applicantextrainformation_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('phone', 'date_of_birth', 'batch')},
        ),
    ]
