# Generated by Django 4.1.7 on 2023-03-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_application_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.TextField(),
        ),
    ]
