# Generated by Django 4.1.7 on 2023-03-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_application_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantextrainformation',
            name='permanent_address',
            field=models.TextField(blank=True, null=True, verbose_name='Permanent Address'),
        ),
    ]
