# Generated by Django 4.2.1 on 2023-05-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_admitcardtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='admitcardtemplate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
