# Generated by Django 4.1.7 on 2023-05-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_admitcardtemplate_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitcardtemplate',
            name='venue',
            field=models.CharField(choices=[('Mirpur Cantonment', 'Mirpur Cantonment'), ('@Jalalabad Cantonment', '@Jalalabad Cantonment'), ('@Mirpur Cantonment', '@Mirpur Cantonment'), ('Jalalabad Cantonment', 'Jalalabad Cantonment')], max_length=255),
        ),
    ]
