# Generated by Django 5.1.1 on 2024-09-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_alter_admitcardtemplate_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitcardtemplate',
            name='venue',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='passing_year',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)]),
        ),
    ]
