# Generated by Django 4.2.19 on 2025-02-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_admitcardtemplate_venue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='passing_year',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)]),
        ),
    ]
