# Generated by Django 4.2.19 on 2025-02-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_alter_application_passing_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='programme',
            field=models.CharField(blank=True, choices=[('CE', 'Civil Engineering - CE'), ('CSE', 'Computer Science and Engineering - CSE'), ('EEE', 'Electrical and Electronic Engineering - EEE'), ('ME', 'Mechanical Engineering - ME'), ('IPE', 'Industrial and Production Engineering - IPE'), ('BBA', 'Bachelor of Business Administration - BBA'), ('MBA', 'Master of Business Administration - MBA')], max_length=255, null=True),
        ),
    ]
