# Generated by Django 4.1.7 on 2023-02-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0006_alter_application_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedApplicantExtraInformation',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Applicant Extra Information',
                'verbose_name_plural': 'Archived Applicant Extra Informations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('application.applicantextrainformation',),
        ),
        migrations.CreateModel(
            name='ArchivedApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Application',
                'verbose_name_plural': 'Archived Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('application.application',),
        ),
        migrations.CreateModel(
            name='ArchivedApplicationStatus',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Application Status',
                'verbose_name_plural': 'Archived Application Statuses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('application.applicationstatus',),
        ),
        migrations.CreateModel(
            name='ArchivedApplicationVerification',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Application Verification',
                'verbose_name_plural': 'Archived Application Verifications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('application.applicationverification',),
        ),
    ]
