# Generated by Django 4.1.7 on 2023-02-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_application_batch'),
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedApplicationPayment',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Application Payment',
                'verbose_name_plural': 'Archived Application Payments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('application.applicationpayment', models.Model),
        ),
    ]
