# Generated by Django 4.1.7 on 2023-02-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_emailcontent_created_at_emailcontent_updated_at_and_more'),
        ('chat', '0013_phonerequest_batch_smsrequest_batch'),
        ('analytics', '0004_remove_applicationnewssource_batch'),
        ('archive', '0002_archivedapplicationpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchievedNewsLetter',
            fields=[
            ],
            options={
                'verbose_name': 'Archived News Letter',
                'verbose_name_plural': 'Archived News Letters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('newsletter.newsletter', models.Model),
        ),
        migrations.CreateModel(
            name='ArchievedSubscriber',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Subscriber',
                'verbose_name_plural': 'Archived Subscribers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('newsletter.subscriber', models.Model),
        ),
        migrations.CreateModel(
            name='ArchivedApplicantWorkingExperience',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Applicant Working Experience',
                'verbose_name_plural': 'Archived Applicant Working Experiences',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('analytics.applicantworkingexperience', models.Model),
        ),
        migrations.CreateModel(
            name='ArchivedApplicationNewsSource',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Application News Source',
                'verbose_name_plural': 'Archived Application News Sources',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('analytics.applicationnewssource', models.Model),
        ),
        migrations.CreateModel(
            name='ArchivedChatRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Chat Request',
                'verbose_name_plural': 'Archived Chat Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chat.chatrequest', models.Model),
        ),
        migrations.CreateModel(
            name='ArchivedPhoneRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Phone Request',
                'verbose_name_plural': 'Archived Phone Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chat.phonerequest', models.Model),
        ),
        migrations.CreateModel(
            name='ArchivedSMSRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Archived SMS Request',
                'verbose_name_plural': 'Archived SMS Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chat.smsrequest', models.Model),
        ),
    ]
