# Generated by Django 4.2.1 on 2023-05-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreference',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=20),
        ),
    ]
