# Generated by Django 4.2.1 on 2023-05-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0002_paymentreference_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreference',
            name='payment_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentreference',
            name='merchant_invoice_number',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentreference',
            name='payer_reference',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
