# Generated by Django 4.2.1 on 2023-05-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0003_paymentreference_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreference',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Initiated', max_length=20),
        ),
    ]
