# Generated by Django 4.2.1 on 2023-05-12 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0004_alter_paymentreference_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreference',
            name='merchant_invoice_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentreference',
            name='payment_id',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
