# Generated by Django 4.2.1 on 2023-05-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0006_requestlog_responselog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='request',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='headers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
