# Generated by Django 4.2.1 on 2023-05-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0007_remove_requestlog_request_requestlog_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responselog',
            name='response',
        ),
        migrations.AddField(
            model_name='responselog',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responselog',
            name='headers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responselog',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
